import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../../lib/supabase';
export default function ResetPassword(){
 const [ready,setReady]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{let alive=true;const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(alive){setReady(!!session);setChecking(false);}});void supabase.auth.getSession().then(({data,error})=>{if(alive){setReady(!!data.session&&!error);setChecking(false);}}).catch(()=>{if(alive){setError('Unable to verify your recovery link. Please try again.');setChecking(false);}});return()=>{alive=false;subscription.unsubscribe();};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return;}setBusy(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setPassword('');setConfirm('');setDone(true);await supabase.auth.signOut();}catch(e){setError(e instanceof Error?e.message:'Password update failed.');}finally{setBusy(false);}}
 return <main className="brand-login min-h-screen flex items-center justify-center p-6"><section className="w-full max-w-md rounded-2xl border bg-white p-8"><img src="/hatsoff-brand.svg" alt="Hatsoff Media"/><h1 className="my-5 text-2xl font-semibold">Reset password</h1>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}{done?<p role="status">Password updated. Sign in with your new password.</p>:checking?<p role="status">Checking recovery link…</p>:!ready?<p role="status">This recovery link is invalid or expired. Return to login to request a new link.</p>:<form onSubmit={e=>void submit(e)} className="grid gap-4"><label>New password<input className="mt-2 w-full border p-3" type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><p className="text-sm text-slate-500">Use at least 12 characters. Your organisation's password rules also apply.</p><label>Confirm password<input className="mt-2 w-full border p-3" type="password" autoComplete="new-password" minLength={12} required value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy}/></label><button type="submit" className="p-3 font-semibold" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>}<Link className="mt-5 inline-block underline" to="/login">Back to login</Link></section></main>;
}
