import {useCallback,useEffect,useState} from 'react';
import {ShieldCheck,Search,Users,CheckCircle2} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';
import type {UserRole} from '../../types/auth';
type Account={id:string;full_name:string;email:string|null;role:UserRole;team_id:string|null;is_active:boolean;sales_access:string|null};
type Directory={accounts:Account[];teams:{id:string;name:string}[]};
const roles:UserRole[]=['admin','director','associate_lead','project_coordinator','team_lead','employee'];
const control='project-input rounded-lg border bg-white px-3 py-2 text-sm';
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function AdminAccessManagement(){
 const {profile,refreshProfile}=useAuth();const admin=profile?.role==='admin';
 const [data,setData]=useState<Directory>({accounts:[],teams:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const [query,setQuery]=useState('');const [filterTeam,setFilterTeam]=useState('');const [filterRole,setFilterRole]=useState('');const [selected,setSelected]=useState<Account|null>(null);
 const [role,setRole]=useState<UserRole>('employee');const [team,setTeam]=useState('');const [sales,setSales]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await supabase.rpc('admin_access_directory');if(r.error)throw new Error(r.error.code==='PGRST202'?'Apply the Team Access & Admin migration to activate this panel.':r.error.message);setData(r.data);}catch(e){setData({accounts:[],teams:[]});setError(e instanceof Error?e.message:'Unable to load access');}finally{setLoading(false);}},[]);
 useEffect(()=>{if(!admin)return;const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[admin,load]);
 if(!admin)return null;
 const choose=(u:Account)=>{setSelected(u);setRole(u.role);setTeam(u.team_id??'');setSales(u.sales_access??'');setSuccess('');};
 const coordination=role==='associate_lead'&&!!team&&data.accounts.some(u=>u.id!==selected?.id&&u.is_active&&u.role==='project_coordinator'&&u.team_id===team);
 const scope=role==='admin'||role==='director'?'All teams':role==='associate_lead'?'Selected team only':role==='team_lead'?'Associate Lead-assigned projects in the selected team':'Assigned or explicitly shared work';
 const projectScope=role==='admin'||role==='director'?'All projects':coordination?'Coordinator team projects':role==='associate_lead'?'Context for projects with this team’s tasks':role==='employee'?'Context for projects with assigned tasks':scope;
 const accounts=data.accounts.filter(u=>(!filterTeam||u.team_id===filterTeam)&&(!filterRole||u.role===filterRole)&&`${u.full_name} ${u.email??''} ${u.id}`.toLowerCase().includes(query.toLowerCase()));
 async function save(){if(!selected)return;setBusy(true);setError('');setSuccess('');try{
  const r=await supabase.rpc('admin_set_access',{p_account:selected.id,p_role:role,p_team:team||null,p_sales:sales||null,p_expected:{role:selected.role,team_id:selected.team_id,sales_access:selected.sales_access}});
  if(r.error)throw new Error(r.error.message);setSelected(null);await load();await refreshProfile();setSuccess('Access saved. Team scope is enforced by the database.');
 }catch(e){setError(e instanceof Error?e.message:'Unable to save access');}finally{setBusy(false);}}
 return <section id="access-management" aria-label="Admin Access Management" className="project-workspace space-y-5 rounded-2xl border bg-white p-6">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-indigo-500"><ShieldCheck size={16}/>Admin Panel</p><h2 className="text-xl font-semibold">Access Management</h2><p className="mt-1 text-sm text-slate-500">Manage verified accounts, team oversight and Sales access in one place.</p></div><button disabled={loading||busy} className="project-button px-3" onClick={()=>{setSelected(null);void load();}}>Refresh access</button></div>
 <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Muskan → Project Coordinators · Ganesh → Creative Clan · Sudeesh → Cut Masters · Vijay → Web Runners · Janani → Digital Ninjas. Select the matching verified account and team; names are not mapped automatically.</p>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{success&&<p role="status" className="flex gap-2 text-sm text-emerald-700"><CheckCircle2 size={18}/>{success}</p>}
 {loading?<p role="status">Loading access…</p>:data.accounts.length>0&&<>
 <div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-xs"><span className="flex gap-1"><Search size={13}/>Find account</span><input className={control} placeholder="Name, email or account ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="grid gap-1 text-xs">Filter team<select aria-label="Filter team" className={control} value={filterTeam} onChange={e=>setFilterTeam(e.target.value)}><option value="">All teams</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="grid gap-1 text-xs">Filter role<select aria-label="Filter role" className={control} value={filterRole} onChange={e=>setFilterRole(e.target.value)}><option value="">All roles</option>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label></div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="max-h-[560px] space-y-2 overflow-y-auto rounded-xl border p-3" aria-label="Accounts">{accounts.map(u=><button disabled={busy} key={u.id} onClick={()=>choose(u)} aria-pressed={selected?.id===u.id} className={`flex w-full items-start gap-3 rounded-xl border p-3 text-left ${selected?.id===u.id?'border-indigo-500 bg-indigo-50':'border-slate-200 bg-white'}`}><span className="coordinator-avatar"><Users size={16}/></span><span className="min-w-0"><strong className="text-sm">{u.full_name||'Unnamed account'}</strong><span className="block break-all text-xs text-slate-500">{u.email||u.id}</span><span className="mt-1 block text-xs text-slate-500">{label(u.role)} · {data.teams.find(t=>t.id===u.team_id)?.name??'No team'}{!u.is_active?' · Inactive':''}</span></span></button>)}{!accounts.length&&<p className="p-3 text-sm text-slate-500">No accounts match these filters.</p>}</div>
 {selected?<form className="space-y-4 rounded-xl border bg-slate-50 p-4" onSubmit={e=>{e.preventDefault();void save();}}><h3 className="font-semibold">Access for {selected.full_name}</h3><p className="break-all text-xs text-slate-500">Account ID: {selected.id}</p><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs">Account role<select aria-label="Account role" className={control} value={role} onChange={e=>setRole(e.target.value as UserRole)}>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label className="grid gap-1 text-xs">Assigned team<select aria-label="Assigned team" className={control} value={team} onChange={e=>setTeam(e.target.value)} required={!['admin','director'].includes(role)}><option value="">No team</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="grid gap-1 text-xs sm:col-span-2">Sales Tracker access<select aria-label="Sales Tracker access" className={control} disabled={role==='admin'} value={role==='admin'?'admin':sales} onChange={e=>setSales(e.target.value)}>{role==='admin'&&<option value="admin">Administrator — full access</option>}<option value="">No Sales access</option><option value="member">Member — own leads</option><option value="viewer">Viewer — all sales, read only</option><option value="manager">Manager — all sales and targets</option></select></label></fieldset>
 <div className="space-y-2 rounded-xl border bg-white p-3"><h4 className="text-sm font-semibold">Effective access preview</h4><dl className="space-y-2 text-xs">{Object.entries({Visibility:scope,Projects:projectScope,'Project assignment':role==='admin'||coordination?'Manage coordinator assignments':'Unavailable','Tasks / Planner / Timesheets':role==='admin'||role==='director'?'All teams':coordination?'Coordinator projects':role==='associate_lead'?'Only tasks and worker records for the selected team':'Authorized work only',Reports:'Limited to accessible records',Announcements:role==='admin'?'Publish and remove':'View only'}).map(([k,v])=><div key={k} className="grid grid-cols-2 gap-3"><dt className="text-slate-500">{k}</dt><dd>{v}</dd></div>)}</dl></div>
 {!selected.is_active&&<p className="text-xs text-amber-700">This account is inactive. Saving its role will not reactivate it.</p>}
 {coordination&&<p className="text-xs text-slate-500">This team contains active Project Coordinators, so its Associate Lead receives project coordination oversight.</p>}
 <p className="text-xs text-slate-500">Saving also aligns linked employee records to this team. Existing project-team mappings and task assignments are preserved.</p><button disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?'Saving…':'Save access'}</button></form>:<div className="grid place-items-center rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Select an account to review its access.</div>}</div></>}
 </section>;
}
