import {useEffect,useState} from 'react';
import {useAuth} from '../../context/AuthContext';
import {getTeamOversight,oversightRoles} from '../../services/teams/teamOversight.service';
import {monthlyTiming,indiaMonth,durationMinutes,deliveryMinutes} from '../../lib/deliveryTiming';
import {formatAssignmentTime} from '../../lib/assignmentTime';
type Data=Awaited<ReturnType<typeof getTeamOversight>>;
export default function TeamPC(){
 const {profile}=useAuth(); const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);
 const [month,setMonth]=useState(indiaMonth(new Date().toISOString())!);const [editor,setEditor]=useState('');
 useEffect(()=>{let cancelled=false;setLoading(true);setData(null);setError('');getTeamOversight().then(d=>{if(!cancelled)setData(d)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[profile?.id,profile?.team_id,profile?.role,revision]);
 if(!oversightRoles.includes(profile?.role??''))return <p role="alert">Team PC is available to leads and associate leads.</p>;
 const totals=monthlyTiming(data?.editorAssignments as Parameters<typeof monthlyTiming>[0] ?? [],month);
 const details=data?.editorAssignments.filter(a=>(!editor||a.employee_id===editor) && indiaMonth(a.deadline_at ?? a.completed_at)===month)??[];
 const untracked=data?.editorAssignments.filter(a=>!a.deadline_at&&!a.completed_at).length??0;
 return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Team PC</h1><p className="mt-2 text-sm text-slate-500">Coordinator activity and Cut Masters delivery timing.</p></div><button disabled={loading} onClick={()=>setRevision(v=>v+1)} className="rounded-xl border px-4 py-2">Refresh</button></header>
 {loading?<p role="status">Loading team activity…</p>:error?<p role="alert" className="rounded-xl bg-yellow-50 p-4">{error}</p>:data&&<>
 <section className="space-y-4"><h2 className="text-lg font-semibold">Project coordinators</h2>{!data.coordinators.length?<p>No project coordinators are linked to your team.</p>:data.coordinators.map(pc=>{const assignments=data.assignments.filter(a=>a.assigned_by===pc.id);return <article key={pc.id} className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">{pc.full_name||'Name unavailable'}{!pc.is_active?' · Inactive':''}</h3><p className="my-3 text-sm">{data.clients.filter(c=>c.created_by===pc.id).length} clients created · {data.projects.filter(p=>p.created_by===pc.id || p.project_members?.some((m:{profile_id:string})=>m.profile_id===pc.id)).length} projects owned/shared · {data.createdTasks.filter(t=>t.created_by===pc.id).length} tasks created · {assignments.length} assignments made · {assignments.filter(a=>a.status==='completed').length} completed</p><details><summary className="cursor-pointer font-medium">View activity and assignment details</summary><ul className="mt-3 space-y-3 text-sm">{data.clients.filter(c=>c.created_by===pc.id).map(c=><li key={c.id}>Client: {c.name} · {formatAssignmentTime(c.created_at)}</li>)}{data.projects.filter(p=>p.created_by===pc.id || p.project_members?.some((m:{profile_id:string})=>m.profile_id===pc.id)).map(p=><li key={p.id}>Project: {p.name} · {p.status} · {formatAssignmentTime(p.created_at)}</li>)}{data.createdTasks.filter(t=>t.created_by===pc.id).map(t=><li key={t.id}>Task created: {t.title} · {t.status} · {formatAssignmentTime(t.created_at)}</li>)}{assignments.map(a=><li key={a.id}>{data.tasks.find(t=>t.id===a.task_id)?.title||'Task unavailable'} → {data.employees.find(e=>e.id===a.employee_id)?.full_name||'Employee ID: '+a.employee_id} · {a.status} · Assigned {formatAssignmentTime(a.assigned_at)} · Due {formatAssignmentTime(a.deadline_at)} · Completed {formatAssignmentTime(a.completed_at)}</li>)}</ul></details></article>})}</section>
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><h2 className="text-lg font-semibold">Cut Masters · Monthly timing</h2><label>Deadline month (IST)<input className="ml-3 rounded-lg border p-2" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><p className="my-4 text-sm text-slate-500">Net delay = minutes late − minutes early, per editor. Completion is the editor’s submission time, not final client approval. Pending work is shown separately and does not earn an early-time offset. Deadline snapshots keep later task edits from changing historical totals.</p>{untracked>0&&<p className="mb-4 text-sm">{untracked} assignments have no recorded deadline or completion and cannot be placed in a month.</p>}
 <div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead><tr>{['Editor','Completed','Late','Early','Net timing','Pending / overdue','Missing timestamps'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{totals.map(t=><tr key={t.employee_id}><td className="p-3">{data.editors.find(e=>e.id===t.employee_id)?.full_name||'Employee unavailable'}</td><td className="p-3">{t.completed}</td><td className="p-3">{durationMinutes(t.lateMinutes)}</td><td className="p-3">{durationMinutes(t.earlyMinutes)}</td><td className="p-3 font-semibold">{durationMinutes(t.netMinutes)} {t.netMinutes>0?'late':t.netMinutes<0?'ahead':'balanced'}</td><td className="p-3">{t.pending} / {t.overdue}</td><td className="p-3">{t.missing}</td></tr>)}</tbody></table></div>{!totals.length&&<p className="py-4">No scheduled editor work for this month.</p>}
 <label className="my-4 block">Editor <select className="ml-3 rounded-lg border p-2" value={editor} onChange={e=>setEditor(e.target.value)}><option value="">All editors</option>{data.editors.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>
 <div className="space-y-3">{details.map(a=>{const delta=a.status==='completed'?deliveryMinutes(a.deadline_at,a.completed_at):null;return <article key={a.id} className="rounded-xl border p-4 text-sm"><p className="font-semibold">{data.tasks.find(t=>t.id===a.task_id)?.title||'Task unavailable'} · {data.editors.find(e=>e.id===a.employee_id)?.full_name}</p><p className="mt-2">Assigned by {data.people.find(p=>p.id===a.assigned_by)?.full_name||'Name unavailable'} · {formatAssignmentTime(a.assigned_at)}</p><p>Deadline {formatAssignmentTime(a.deadline_at)} · Completed {formatAssignmentTime(a.completed_at)}</p><p>{a.status} · {delta===null?'Timing not calculated':durationMinutes(delta)+(delta>0?' late':delta<0?' early':' on time')}</p></article>})}</div></section></>}
 </div>;
}
