import {useEffect,useState} from 'react';
import './TeamPC.css';
import {useAuth} from '../../context/AuthContext';
import {getTeamOversight,oversightRoles} from '../../services/teams/teamOversight.service';
import {monthlyTiming,indiaMonth,durationMinutes,deliveryMinutes} from '../../lib/deliveryTiming';
import {formatAssignmentTime} from '../../lib/assignmentTime';
type Data=Awaited<ReturnType<typeof getTeamOversight>>;
export default function TeamPC(){
 const {profile}=useAuth(); const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);
 const [coordinator,setCoordinator]=useState('');
 const [month,setMonth]=useState(indiaMonth(new Date().toISOString())!);const [editor,setEditor]=useState('');const [team,setTeam]=useState('');
 useEffect(()=>{let cancelled=false;setLoading(true);setData(null);setError('');getTeamOversight().then(d=>{if(!cancelled)setData(d)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[profile?.id,profile?.team_id,profile?.role,revision]);
 if(!oversightRoles.includes(profile?.role??''))return <p role="alert">Team PC is available to leads and associate leads.</p>;
 const selectedCoordinator=data?.coordinators.some(p=>p.id===coordinator)?coordinator:'';
 const visibleCoordinators=data?.coordinators.filter(p=>!selectedCoordinator||p.id===selectedCoordinator)??[];
 const members=data?.teamMembers.filter(e=>!team||(team==='unassigned'?!e.team_id:e.team_id===team))??[];
 const selectedAssignments=data?.teamAssignments.filter(a=>members.some(e=>e.id===a.employee_id)&&(!editor||a.employee_id===editor))??[];
 const totals=monthlyTiming(selectedAssignments as Parameters<typeof monthlyTiming>[0],month);
 const details=selectedAssignments.filter(a=> indiaMonth(a.deadline_at ?? a.completed_at)===month)??[];
 const untracked=selectedAssignments.filter(a=>!a.deadline_at&&!a.completed_at).length??0;
 return <div className="team-pc"><header className="flex flex-wrap items-center justify-between gap-4"><div><span className="pc-eyebrow">TEAM OVERSIGHT</span><h1 className="text-2xl font-semibold">Team PC</h1><p className="mt-2 text-sm text-slate-500">Coordinator activity and delivery timing across every team.</p></div><button disabled={loading} onClick={()=>setRevision(v=>v+1)} className="rounded-xl border px-4 py-2">Refresh</button></header>
 {loading?<p role="status">Loading team activity…</p>:error?<p role="alert" className="rounded-xl bg-yellow-50 p-4">{error}</p>:data&&<>
 <section className="pc-coordinators"><div className="pc-coordinator-toolbar"><h2 className="text-lg font-semibold">Project coordinators</h2><label>Coordinator<select value={selectedCoordinator} onChange={e=>setCoordinator(e.target.value)}><option value="">All coordinators</option>{data.coordinators.map(p=><option key={p.id} value={p.id}>{p.full_name||'Name unavailable'} · {p.role.replaceAll('_',' ')}</option>)}</select></label></div><p className="pc-directory-help">Active coordinator accounts and Flow Force supervisors appear automatically from their role and team.</p>{!data.coordinators.length?<div className="pc-empty"><span className="pc-empty-symbol">◇</span><h3>No coordinators linked yet</h3><p>No project coordinators are linked to your team. Ask an administrator to check team membership.</p></div>:visibleCoordinators.map(pc=>{const assignments=data.assignments.filter(a=>a.assigned_by===pc.id);return <article key={pc.id} className="pc-coordinator-card"><h3 className="font-semibold">{pc.full_name||'Name unavailable'}{!pc.is_active?' · Inactive':''}</h3><p className="my-3 text-sm">{data.clients.filter(c=>c.created_by===pc.id).length} clients created · {data.projects.filter(p=>p.created_by===pc.id || p.project_members?.some((m:{profile_id:string})=>m.profile_id===pc.id)).length} projects owned/shared · {data.createdTasks.filter(t=>t.created_by===pc.id).length} tasks created · {assignments.length} assignments made · {assignments.filter(a=>a.status==='completed').length} completed</p><details><summary className="cursor-pointer font-medium">View activity and assignment details</summary><ul className="mt-3 space-y-3 text-sm">{data.clients.filter(c=>c.created_by===pc.id).map(c=><li key={c.id}>Client: {c.name} · {formatAssignmentTime(c.created_at)}</li>)}{data.projects.filter(p=>p.created_by===pc.id || p.project_members?.some((m:{profile_id:string})=>m.profile_id===pc.id)).map(p=><li key={p.id}>Project: {p.name} · {p.status} · {formatAssignmentTime(p.created_at)}</li>)}{data.createdTasks.filter(t=>t.created_by===pc.id).map(t=><li key={t.id}>Task created: {t.title} · {t.status} · {formatAssignmentTime(t.created_at)}</li>)}{assignments.map(a=><li key={a.id}>{data.tasks.find(t=>t.id===a.task_id)?.title||'Task unavailable'} → {data.employees.find(e=>e.id===a.employee_id)?.full_name||'Employee ID: '+a.employee_id} · {a.status} · Assigned {formatAssignmentTime(a.assigned_at)} · Due {formatAssignmentTime(a.deadline_at)} · Completed {formatAssignmentTime(a.completed_at)}</li>)}</ul></details></article>})}</section>
 <section className="pc-timing"><div className="flex flex-wrap justify-between gap-4"><h2 className="text-lg font-semibold">All teams · Monthly timing</h2><label>Deadline month (IST)<input className="ml-3 rounded-lg border p-2" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><details className="pc-explainer"><summary>How monthly timing is calculated</summary><p>Net delay = minutes late − minutes early, per employee. Completion is the employee’s submission time, not final client approval. Pending work is shown separately and does not earn an early-time offset. Deadline snapshots keep later task edits from changing historical totals.</p></details>{untracked>0&&<p className="mb-4 text-sm">{untracked} assignments have no recorded deadline or completion and cannot be placed in a month.</p>}
 <div className="pc-table-wrap"><table className="w-full min-w-[750px] text-left text-sm"><thead><tr>{['Employee / team','Completed','Late','Early','Net timing','Pending / overdue','Missing timestamps'].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{totals.map(t=><tr key={t.employee_id}><td className="p-3">{data.teamMembers.find(e=>e.id===t.employee_id)?.full_name||'Employee unavailable'}<small className="pc-team-name">{data.teams.find(team=>team.id===data.teamMembers.find(e=>e.id===t.employee_id)?.team_id)?.name||'No team assigned'}</small></td><td className="p-3">{t.completed}</td><td className="p-3">{durationMinutes(t.lateMinutes)}</td><td className="p-3">{durationMinutes(t.earlyMinutes)}</td><td className="p-3 font-semibold">{durationMinutes(t.netMinutes)} {t.netMinutes>0?'late':t.netMinutes<0?'ahead':'balanced'}</td><td className="p-3">{t.pending} / {t.overdue}</td><td className="p-3">{t.missing}</td></tr>)}</tbody></table></div>{!totals.length&&<div className="pc-empty"><span className="pc-empty-symbol">◷</span><h3>No scheduled deliveries</h3><p>No scheduled team work for this month. Assignments with deadlines will appear here.</p></div>}
 <div className="pc-team-filters"><label>Team <select value={team} onChange={e=>{setTeam(e.target.value);setEditor('')}}><option value="">All teams</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}<option value="unassigned">No team assigned</option></select></label></div><label className="pc-editor-filter">Employee <select className="ml-3 rounded-lg border p-2" value={editor} onChange={e=>setEditor(e.target.value)}><option value="">All employees</option>{members.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>
 <div className="pc-assignment-list">{details.map(a=>{const delta=a.status==='completed'?deliveryMinutes(a.deadline_at,a.completed_at):null;return <article key={a.id} className="pc-assignment-card"><p className="font-semibold">{data.tasks.find(t=>t.id===a.task_id)?.title||'Task unavailable'} · {data.teamMembers.find(e=>e.id===a.employee_id)?.full_name}</p><p className="mt-2">Assigned by {data.people.find(p=>p.id===a.assigned_by)?.full_name||'Name unavailable'} · {formatAssignmentTime(a.assigned_at)}</p><p>Deadline {formatAssignmentTime(a.deadline_at)} · Completed {formatAssignmentTime(a.completed_at)}</p><p>{a.status} · {delta===null?'Timing not calculated':durationMinutes(delta)+(delta>0?' late':delta<0?' early':' on time')}</p></article>})}</div></section></>}
 </div>;
}
