import {useCallback,useEffect,useState} from 'react';
import {ImagePlus,Megaphone} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';
type Announcement={id:string;title:string;image_data:string;created_at:string};
export default function Announcements(){
 const {profile}=useAuth();const admin=profile?.role==='admin';const [rows,setRows]=useState<Announcement[]>([]);const [editing,setEditing]=useState(false);const [title,setTitle]=useState('');const [image,setImage]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async()=>{const r=await supabase.from('workspace_announcements').select('*').order('created_at',{ascending:false}).limit(10);if(r.error){if(admin)setError('Announcements are unavailable. Apply the workspace updates migration to enable publishing.');return;}setRows(r.data);},[admin]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);const c=supabase.channel('dashboard-announcements').on('postgres_changes',{event:'*',schema:'public',table:'workspace_announcements'},()=>void load()).subscribe();return()=>{clearTimeout(t);void supabase.removeChannel(c);};},[load]);
 async function selectFile(file?:File){if(!file)return;setError('');setBusy(true);try{
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('Choose a JPG, PNG or WebP image up to 10 MB.');
  const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/bitmap.width,1600/bitmap.height);const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image processing is unavailable');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/webp',.82);if(data.length>2000000)throw new Error('Image is too detailed; choose a smaller image.');setImage(data);
 }catch(e){setError(e instanceof Error?e.message:'Unable to read image');}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError('');const r=await supabase.from('workspace_announcements').insert({title:title.trim(),image_data:image,created_by:profile?.id});if(r.error)setError(r.error.message);else{setEditing(false);setImage('');setTitle('');await load();}setBusy(false);}
 async function remove(id:string){setBusy(true);setError('');const r=await supabase.from('workspace_announcements').delete().eq('id',id).select('id').single();if(r.error)setError(r.error.message);else await load();setBusy(false);}
 if(!admin&&!rows.length)return null;
 return <section aria-label="Announcements" className="space-y-4 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-semibold"><Megaphone size={18}/>Announcements</h2>{admin&&<button className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm" onClick={()=>setEditing(!editing)}><ImagePlus size={16}/>{editing?'Cancel':'Add image announcement'}</button>}</div>
 {error&&<p role="alert" className="text-sm text-amber-700">{error}</p>}
 {editing&&admin&&<form className="grid gap-3" onSubmit={e=>{e.preventDefault();void publish();}}><label className="grid gap-1 text-sm">Announcement title / image description<input className="rounded-lg border p-2" maxLength={180} required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="grid gap-1 text-sm">Announcement image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void selectFile(e.target.files?.[0])}/></label>{image&&<img src={image} alt={title||'Announcement preview'} className="max-h-80 rounded-xl object-contain"/>}<button disabled={busy||!image||!title.trim()} className="justify-self-start rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{busy?'Saving…':'Publish announcement'}</button></form>}
 <div className="grid gap-4 md:grid-cols-2">{rows.map(row=><article key={row.id} className="overflow-hidden rounded-xl border"><img src={row.image_data} alt={row.title} className="max-h-[420px] w-full object-contain"/><div className="flex items-center justify-between gap-3 p-3"><h3 className="text-sm font-medium">{row.title}</h3>{admin&&<button disabled={busy} className="text-xs underline" onClick={()=>void remove(row.id)}>Remove announcement</button>}</div></article>)}</div>
 {!rows.length&&!editing&&!error&&<p className="text-sm text-slate-500">No announcements yet.</p>}</section>;
}
